//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WestRockDataPonchesPRO.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WestRockDataPonchesPRO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap action {
            get {
                object obj = ResourceManager.GetObject("action", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos; &apos;.
        /// </summary>
        internal static string CHAR_FILL {
            get {
                return ResourceManager.GetString("CHAR_FILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  .
        /// </summary>
        internal static string CHAR_SEPARATOR {
            get {
                return ResourceManager.GetString("CHAR_SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provider = Microsoft.Jet.OLEDB.4.0; Data Source = C:\BioTrack Software\BioAdmin\Data\BDBioAdmin.mdb.
        /// </summary>
        internal static string CONN_STRING_ACCESS {
            get {
                return ResourceManager.GetString("CONN_STRING_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server=172.23.24.82\SQLEXPRESS,1533;Database=BDBioAdminSQL;UID=etiquetas;PWD=123;.
        /// </summary>
        internal static string CONN_STRING_SQL {
            get {
                return ResourceManager.GetString("CONN_STRING_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BDBioAdminSQL.
        /// </summary>
        internal static string DATABASE_NAME {
            get {
                return ResourceManager.GetString("DATABASE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C:\bt\reportes\.
        /// </summary>
        internal static string DIRECTORY_REPOTRS {
            get {
                return ResourceManager.GetString("DIRECTORY_REPOTRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BiotrackData.txt.
        /// </summary>
        internal static string FILENAME {
            get {
                return ResourceManager.GetString("FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 123.
        /// </summary>
        internal static string PASSWORD_SQL {
            get {
                return ResourceManager.GetString("PASSWORD_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C:\Venturessoft\Clkstation\VSM\Interface\Checadas\.
        /// </summary>
        internal static string PATH_FILE_TXT {
            get {
                return ResourceManager.GetString("PATH_FILE_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1533.
        /// </summary>
        internal static string PORT_COMM {
            get {
                return ResourceManager.GetString("PORT_COMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT a.IdUser,b.Name,a.RecordTime,a.MachineNumber,b.ExternalReference,b.IdentificationNumber FROM [BDBioAdminSQL].[dbo].[Record] a LEFT JOIN [BDBioAdminSQL].[dbo].[User] b ON a.IdUser = b.IdUser WHERE DAY(a.RecordTime) = DAY(GETDATE()) AND MONTH(a.RecordTime) = MONTH(GETDATE()) AND YEAR(a.RecordTime) = YEAR(GETDATE()).
        /// </summary>
        internal static string QUERY_STRING_SQL {
            get {
                return ResourceManager.GetString("QUERY_STRING_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5.
        /// </summary>
        internal static string RANGLE_MIN_SALIDAS {
            get {
                return ResourceManager.GetString("RANGLE_MIN_SALIDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 172.23.24.82\SQLEXPRESS.
        /// </summary>
        internal static string SERVER_NAME {
            get {
                return ResourceManager.GetString("SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a etiquetas.
        /// </summary>
        internal static string USER_SQL {
            get {
                return ResourceManager.GetString("USER_SQL", resourceCulture);
            }
        }
    }
}
